//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetParts.Libraries.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Msg {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Msg() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetParts.Libraries.Lang.Msg", typeof(Msg).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} é obrigatório..
        /// </summary>
        public static string MSG_E001 {
            get {
                return ResourceManager.GetString("MSG_E001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} deve ter no mínimo {1} caracteres..
        /// </summary>
        public static string MSG_E002 {
            get {
                return ResourceManager.GetString("MSG_E002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} deve ter no máximo {1} caracteres..
        /// </summary>
        public static string MSG_E003 {
            get {
                return ResourceManager.GetString("MSG_E003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} não é válido..
        /// </summary>
        public static string MSG_E004 {
            get {
                return ResourceManager.GetString("MSG_E004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor do campo {0} senha não confere com o campo {1} !.
        /// </summary>
        public static string MSG_E005 {
            get {
                return ResourceManager.GetString("MSG_E005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor do campo {0} está não se entra entre {1} e {2}!.
        /// </summary>
        public static string MSG_E006 {
            get {
                return ResourceManager.GetString("MSG_E006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantidade não pode ser 0, se quiser remova o item do carrinho..
        /// </summary>
        public static string MSG_E007 {
            get {
                return ResourceManager.GetString("MSG_E007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantidade solicitada é maior da disponível em estoque..
        /// </summary>
        public static string MSG_E008 {
            get {
                return ResourceManager.GetString("MSG_E008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi selecionado o tipo de envio!.
        /// </summary>
        public static string MSG_E009 {
            get {
                return ResourceManager.GetString("MSG_E009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi selecionado produtos para compra!.
        /// </summary>
        public static string MSG_E010 {
            get {
                return ResourceManager.GetString("MSG_E010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} já está sendo utilizado!.
        /// </summary>
        public static string MSG_E011 {
            get {
                return ResourceManager.GetString("MSG_E011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível deletar categoria vinculada..
        /// </summary>
        public static string MSG_E012 {
            get {
                return ResourceManager.GetString("MSG_E012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possivel deletar categoria com produto vinculado..
        /// </summary>
        public static string MSG_E013 {
            get {
                return ResourceManager.GetString("MSG_E013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email não encontrado na Base de Dados, verifique o email digitado..
        /// </summary>
        public static string MSG_E014 {
            get {
                return ResourceManager.GetString("MSG_E014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link recuperar senha inválido!.
        /// </summary>
        public static string MSG_E015 {
            get {
                return ResourceManager.GetString("MSG_E015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro salvo com sucesso!.
        /// </summary>
        public static string MSG_S001 {
            get {
                return ResourceManager.GetString("MSG_S001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro excluído com sucesso!.
        /// </summary>
        public static string MSG_S002 {
            get {
                return ResourceManager.GetString("MSG_S002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha enviada com sucesso para o e-mail..
        /// </summary>
        public static string MSG_S003 {
            get {
                return ResourceManager.GetString("MSG_S003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro salvo com sucesso, a senha foi enviada para o e-mail cadastrado..
        /// </summary>
        public static string MSG_S004 {
            get {
                return ResourceManager.GetString("MSG_S004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assistência Técnica ativada com sucesso!.
        /// </summary>
        public static string MSG_S005 {
            get {
                return ResourceManager.GetString("MSG_S005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensagem enviado com sucesso, verifique seu email..
        /// </summary>
        public static string MSG_S006 {
            get {
                return ResourceManager.GetString("MSG_S006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha alterada com sucesso!.
        /// </summary>
        public static string MSG_S007 {
            get {
                return ResourceManager.GetString("MSG_S007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário não encontrado, verifique o e-mail e senha!.
        /// </summary>
        public static string MSG_S016 {
            get {
                return ResourceManager.GetString("MSG_S016", resourceCulture);
            }
        }
    }
}
